name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '.streamlit/**'
      - 'app/**'
      - 'assets/**'
      - 'Dockerfile'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create firebase-config file
        run: |
          echo '${{ secrets.FIREBASE_CONFIG }}' > firebase-config.json

      - name: Create .env file
        run: |
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" > .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: areebahmeddd/denthic
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Trigger DigitalOcean Deployment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DO_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://api.digitalocean.com/v2/apps/31ccb161-5b1e-4e6f-b4fc-8b5310e87172/deployments"
